version: '3'
services:
  web:
    build: .
    restart: always
    volumes:
      - .:/go/src/gitlab.com/arnaud-web/neli-webservices
      - /app/neli:/assets
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    command: bash -c "seeds --config ./docker.ini && neli-webservices --config ./docker.ini"
  mysql:
      image: mysql:5.7.22
      container_name: ${DB_HOST}
      restart: always
      env_file:
          - ".env"
      environment:
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      ports:
          - "3306:3306"
      volumes:
          - "./data/db/mysql:/var/lib/mysql"
          - ./__resources__/dump/database.sql:/data/application/database.sql
      command: --init-file /data/application/database.sql